substitutions:
  name: "pc-switch"
  friendly_name: "PC Switch"
  # Fork of ajfriesen.pc-switch
  project_name: "OstenTV.pc-switch"
  project_version: "1.1.6"

esphome:
  platform: ESP8266
  board: nodemcuv2
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ${project_name}
    version: ${project_version}

logger:
api:
ota:
  platform: esphome
wifi:
  ap: {}

captive_portal:

improv_serial:

dashboard_import:
  package_import_url: github://OstenTV/pc-switch/pc-switch.yaml@main
  import_full_config: false

sensor:
  - platform: wifi_signal
    name: "pc-switch WiFi Signal"
    update_interval: 60s

switch:
  - platform: gpio
    pin: D6
    id: power_pin
    internal: true

  - platform: template
    name: "Power Switch"
    id: power_switch
    internal: true
    turn_on_action:
      - switch.turn_on: power_pin
      - delay: 300ms
      - switch.turn_off: power_pin

  - platform: template
    name: "Power Switch Force"
    id: power_switch_force
    internal: true
    turn_on_action:
      - switch.turn_on: power_pin
      - delay: 5000ms
      - switch.turn_off: power_pin

  - platform: gpio
    pin: D7
    id: reset_pin
    internal: true

  - platform: template
    name: "Reset Switch"
    id: reset_switch
    internal: true
    turn_on_action:
      - switch.turn_on: reset_pin
      - delay: 300ms
      - switch.turn_off: reset_pin

binary_sensor:
  - platform: gpio
    pin: D0
    id: pc_power_sensor
    name: "Power State"
    device_class: power
    icon: "mdi:desktop-classic"

button:
  - platform: template
    name: "Power Button"
    id: power_button
    icon: "mdi:power-standby"
    on_press:
      then:
        - switch.toggle: power_switch

  - platform: template
    name: "Force Power Off"
    id: force_power_off
    icon: "mdi:power-plug-off"
    on_press:
      then:
        - switch.toggle: power_switch_force

  - platform: template
    name: "Reset Button"
    id: reset_button
    icon: "mdi:restart"
    on_press:
      then:
        - switch.toggle: reset_switch
