substitutions:
  name: "pc-switch"
  friendly_name: "PC Switch"
  # Fork of ajfriesen.pc-switch
  project_name: "OstenTV.pc-switch"
  project_version: "1.1.4"

esphome:
  platform: ESP8266
  board: nodemcuv2
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ${project_name}
    version: ${project_version}

logger:
api:
ota:
wifi:
  ap: {}

captive_portal:

improv_serial:

dashboard_import:
  package_import_url: github://OstenTV/pc-switch/pc-switch.yaml@main
  import_full_config: false

switch:
  - platform: gpio
    pin: 
      number: D6
      allow_other_uses: true
    id: power_switch
    internal: true
    on_turn_on:
    - delay: 300ms
    - switch.turn_off: power_switch

  - platform: gpio
    pin: 
      number: D6
      allow_other_uses: true
    id: power_switch_force
    internal: true
    on_turn_on:
    - delay: 5000ms
    - switch.turn_off: power_switch_force

  - platform: gpio
    pin: D7
    id: reset_switch
    on_turn_on:
    - delay: 300ms
    - switch.turn_off: reset_switch

binary_sensor:
  - platform: gpio
    pin: D0
    id: pc_power_sensor
    name: "Power State"
    device_class: power
    icon: "mdi:desktop-classic"

button:
  - platform: template
    name: "Power Button"
    id: power_button
    icon: "mdi:power-standby"
    on_press:
      then:
        - switch.toggle: power_switch

  - platform: template
    name: "Force Power Off"
    id: force_power_off
    icon: "mdi:power-plug-off"
    on_press:
      then:
        - switch.toggle: power_switch_force

  - platform: template
    name: "Reset Button"
    id: reset_button
    icon: "mdi:restart"
    on_press:
      then:
        - switch.toggle: reset_switch
